default:
# Podemos agregar cualquier configuracion general en esta sección
  external_api:
    server: "database_server"
    port: "8080"
  mlconfig:
    general:
      random_state: 42
local:
  mlconfig:
    mlflowconfig:
      server: "localhost"
      port: "5000"
      experiment_name: "Turkish Music Emotion Classification"
      enabled: true
    logger:
      log_level : "DEBUG"
      log_format : "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      log_date_format : "%Y-%m-%d %H:%M:%S"
      log_stream : "stdout"
    data_loader:
      test_size: 0.3
      outlier_k: 3
    model_trainer:
      iterations: 30
      cv_folds: 5                   
      scoring: "accuracy"               
      verbose: 2 
    feature_engine:
      k_features: 15 
      n_components: 8
            
testing:
  mlconfig:
    mlflowconfig:
      server: "0.0.0.0"
      port: "5000"
      experiment_name: "Turkish Music Emotion Classification"
      enabled: true
    logger:
      log_level : "DEBUG"
      log_format : "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      log_date_format : "%Y-%m-%d %H:%M:%S"
      log_stream : "stdout"
    data_loader:
      test_size: 0.3
      outlier_k: 3
    model_trainer:
      iterations: 30
      cv_folds: 5                   
      scoring: "accuracy"               
      verbose: 2 
    feature_engine:
      k_features: 15 
      n_components: 8

produccion:
  mlconfig:
    mlflowconfig:
      server: "0.0.0.0"
      port: "5000"
      experiment_name: "Turkish Music Emotion Classification"
      enabled: true
    logger:
      log_level : "DEBUG"
      log_format : "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      log_date_format : "%Y-%m-%d %H:%M:%S"
      log_stream : "stdout"